INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 1', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 1', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 1', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 2', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 2', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 2', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 3', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 3', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 3', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 4', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 4', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 4', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 5', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 5', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 5', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 6', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 6', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 6', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 7', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 7', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 7', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 8', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 8', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 8', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 9', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 9', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 9', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Books 10', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Electronics 10', NOW());
INSERT INTO TB_CATEGORY (NAME, created_At) VALUES('Computers 10', NOW());